[bump]
features_always_bump_minor = true
breakage_always_bump_major = false
custom_major_increment_regex = "^breaking"

[git]
conventional_commits = true
filter_unconventional = true
limit_commits_to_path = true
tag_pattern = "[a-zA-Z0-9-]+-v[0-9]+\\.[0-9]+\\.[0-9]+$"
commit_parsers = [
  { message = "^breaking", group = "Breaking Changes", bump_type = "major" },
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = ".*", skip = true },
]

[changelog]
header = """
# Changelog\n
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}]({{ env.CI_REPO_LINK | default(value="http://localhost:3000/netanelzucaim/semantic") }}/releases/tag/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d %H:%M") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        * {{ commit.message | upper_first }}
    {% endfor %}
{% endfor %}\n
"""

