clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      tags: true

when:
  - event: push
    branch: main


steps:
  - name: Fetch PR body
    image: alpine/curl:latest
    environment:
      GITEA_TOKEN: 3935ecfe08a1f2baf043bde1a317b337f60650d0
      GITEA_URL: http://gitea-http.gitea.svc.cluster.local:3000
    commands:
      - |
        PR_BODY=$(curl -sf \
          -H "Authorization: token $GITEA_TOKEN" \
          "$GITEA_URL/api/v1/repos/$CI_REPO/pulls?state=closed&limit=50" \
          | grep -o '"body":"[^"]*"' | head -1 \
          | sed 's/"body":"//;s/"$//')
        echo "$PR_BODY" > pr_body.txt
        echo ">>> PR Body: $PR_BODY"

  - name: Run release
    image: netanelzucaim123/python-git-cliff:latest
    environment:
      PLUGIN_MONOREPO_PATH: "."
      GITEA_TOKEN: 3935ecfe08a1f2baf043bde1a317b337f60650d0
      GITEA_URL: http://gitea-http.gitea.svc.cluster.local:3000
    commands:
      - export PR_BODY="$(cat pr_body.txt)"
      - echo ">>> Running release for PR body:" && echo "$PR_BODY"
      - python3 release.py

  - name: Push changelogs to Git
    image: netanelzucaim123/python-git-cliff:latest
    environment:
      GITEA_TOKEN: 3935ecfe08a1f2baf043bde1a317b337f60650d0
      GITEA_URL: http://gitea-http.gitea.svc.cluster.local:3000
    commands:
      - git config --global user.email "ci-bot@example.com"
      - git config --global user.name "CI Bot"
      - git add -A
      - git remote set-url $GITEA_URL
      - |
        if ! git diff --cached --quiet; then
          git commit -m "chore(release): update CHANGELOG.md files [skip ci]"
          git push origin HEAD:main
        else
          echo "No changelog changes to commit."
        fi




