when:
  - event: push
    branch: master
    path:
      include: ['docs/**']

steps:
  - name: Publish Docs to Confluence
    image: artifactory.company.zucaim/woodpecker/plugins/docs2confluence:67d76b44a29
    settings:
      confluence_url: https://confluence.company.zucaim
      confluence_token:
        from_secret: confluence_token
      confluence_space: WOOD
      confluence_root_folder: Plugins
      docs_root_folder: docs
